name: ci

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: install rust
        uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: rustfmt, clippy

      - name: install just
        uses: extractions/setup-just@v4

      - name: run checks
        run: just check

      - name: build
        run: just build
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: build via nix flake
        run: nix build
